# Site settings
title: Daniel Saez
header-img: img/about-bg.jpg
email: your-email@yourdomain.com
copyright_name: Daniel Sáez Trigueros
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
github_username:  d4nst
linkedin_username:  danielsaeztrigueros
email_username:  danst.18@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

disqus: danst