# Site settings
title: Daniel Saez
header-img: img/header.png
email: danst.18@gmail.com
copyright_name: Daniel Sáez Trigueros
description: "A singular blog"
baseurl: ""
url: "https://d4nst.github.io/"
github_username:  d4nst
linkedin_username:  danielsaeztrigueros

# Google analytics
# google_tracking_id:

# Disqus shortname
disqus: danst

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

